name: Lint Check

on:
  push:
    branches:
      - main
      - nilo/workflow-001
  pull_request:
    branches:
      - main
      - nilo/workflow-001

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn eslint .
